config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  resources :categories
  resources :deal_categories, only: [:new, :create]
  resources :deals


     authenticated :user do
      root to: 'categories#index'
    end
  
    devise_scope :user do
      root to: 'devise/sessions#splash', as: :splash_root
    end

    get '/older_categories' => "categories#older_index"
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "home#index"
  # resource :home
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all

    elsif user.role == 'user'
      can :read, :all, user_id: user.id
      can :create, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  # has_one_attached :icon
  has_many :deal_categories, dependent: :destroy
  has_many :deals, through: :deal_categories

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :deal_categories, dependent: :destroy
  has_many :categories, through: :deal_categories

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/deal_category.rb
class DealCategory < ApplicationRecord
  belongs_to :category
  belongs_to :deal

  # validates :category_id, presence: true
  # validates :deal_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :deals, dependent: :destroy

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user: current_user).includes(:deal_categories).order(created_at: :desc).limit(4)
    @name = current_user.name
  end

  def older_index
    @categories = Category.where(user: current_user).includes(:deal_categories).order(created_at: :asc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @deal_categories = DealCategory.includes(:deal).where(category_id: @category).order(created_at: :desc)
    @total = 0
    @deal_categories.each { |e| @total += e.deal.amount }
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    category = Category.new(category_params)
    category.user = current_user
    if category.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deal_categories_controller.rb
class DealCategoriesController < ApplicationController
  def new
    @deal = Deal.new
    @categories = Category.where(user: current_user)
  end

  def create
    deal = Deal.create(name: deal_params[:name], author_id: current_user.id, amount: deal_params[:amount])

    if deal.save
      DealCategory.create(deal_id: deal.id, category_id: params[:category])
      redirect_to categories_path(params[:categories])
    else
      flash[:notice] = 'Error during creation'
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:name, :amount)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deal_categories_helper.rb
module DealCategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, class: 'd-flex flex-column') do |form| %>
  <div class="d-flex justify-content-between top p-2">
    <%= link_to root_path, class: 'text-light h1' do %>
        <i class="bi bi-arrow-left"></i>
    <% end %>
    <h2 class='text-light h1'>NEW CATEGORY</h2>
    <%= form.submit 'Save'%>
  </div>
   <div class="p-2">
    <%= form.text_field :name, placeholder: 'Name', class: 'form-control mb-2' %>
   </div>
   <div class="p-2">
    <%= form.text_field :icon, placeholder: 'Icon\'s link', class: 'form-control mb-2' %>
   </div>
<% end %>

app/views/categories/index.html.erb
<div class="d-flex justify-content-between top text-light p-2">
  <a href="#" class="text-light"><i class="bi bi-list h1"></i></a>
  <h1>CATEGORIES</h1>
  <a href="#" class="text-light"><i class="bi bi-search h1"></i></a>
</div>
<ul class="top d-flex justify-content-center gap-1 pb-1 list-unstyled">
  <li><%= link_to_unless_current("Most recent", root_path ) %><li>
  <li><%= link_to_unless_current("Most ancient",  older_categories_path ) %><li>
</ul>

<% if !@categories.empty? %>
  <div id="categories" class="p-5">
  <% @categories.each do |category| %>
  <div class="category d-flex border mb-1 p-1 m-3">
      <div class="logo me-2 col-3" style="background-image: url(<%= category.icon %>)"></div>
      <div class="col-3">
        <%= link_to category_path(category), class: 'text-decoration-none' do %>
          <%= category.name %>
        <% end %>
        <p><%= category.created_at.strftime("%d %h %Y")  %></p>
      </div>
      <p></p>
      <% @total = 0 %>
      <% category.deal_categories.each { |e| @total += e.deal.amount }%>
      <p class="text-end col-1">Total: $<%= @total %></p>
    </div>
  <% end %>
  </div>
<% else %>
  <p class="p-2">No category added yet</p>
<% end %>

<div class="text-light footer d-flex justify-content-center p-3">
  <%= link_to "Add new category", new_category_path, class: 'btn border border-light p-2' %>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/older_index.html.erb
<div class="d-flex justify-content-between top text-light p-2">
  <a href="#" class="text-light"><i class="bi bi-list h1"></i></a>
  <h1>CATEGORIES</h1>
  <a href="#" class="text-light"><i class="bi bi-search h1"></i></a>
</div>
<ul class="top d-flex justify-content-center gap-2 list-unstyled pb-2">
  <li><%= link_to_unless_current("Most recent", root_path ) %><li>
  <li><%= link_to_unless_current("Most ancient",  older_categories_path ) %><li>
</ul>

<% if !@categories.empty? %>
  <div id="categories" class="p-5">
    <% @categories.each do |category| %>
      <div class="category d-flex border mb-1 p-1 m-2">
        <div class="logo me-2 col-3" style="background-image: url(<%= category.icon %>)"></div>
        <div class="col-6">
          <%= link_to category_path(category), class: 'text-decoration-none' do %>
            <%= category.name %>
          <% end %>
          <p><%= category.created_at.strftime("%d %h %Y")  %></p>
        </div>
        <div class="col-1">
          <% @total = 0 %>
          <% category.deal_categories.each { |e| @total += e.deal.amount }%>
          <p class="text-end">Total: $<%= @total %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="p-2">No category added yet</p>
<% end %>

<div class="text-light footer d-flex justify-content-center p-3">
  <%= link_to "Add new category", new_category_path, class: 'btn border border-light p-2' %>
</div>

app/views/categories/show.html.erb
<div class="d-flex justify-content-between top p-2">
    <%= link_to root_path, class: 'text-light h1' do %>
        <i class="bi bi-arrow-left"></i>
    <% end %>
    <h2 class='text-light h1'>DEAL</h2>
    <p></p>
</div>

<% if @deal_categories.size > 0%>
<div id="categories" class="p-2">
  <p class="d-flex justify-content-between">
    <span>Total payment:</span><span class='font-weight-bold'>$<%= @total %></span>
  </p>
  <% @deal_categories.each do |category| %>
    <div class="d-flex justify-content-between align-items border bg-light mt-2 mb-2 p-1">
      <div class="d-flex flex-column">
        <p>  
         <%= category.deal.name %>
        </p>
        <small class='text-secondary'>
          <%= category.created_at.strftime("%d %h %Y")%> at <%=category.created_at.strftime("%l.%M%P")%>
        </small>
      </div>
      <p class='font-weight-bold font-italic'>$<%= category.deal.amount %></p>
    </div>
  <% end %>
 <% else %>
    <p class="p-2">No deal added yet for this category</p>
 <% end %>
  <div class="text-light footer d-flex justify-content-center p-3">
    <%= link_to "Add new deal", new_deal_category_path, class: 'btn border border-light p-2' %>
  </div>
</div>

app/views/deal_categories/new.html.erb
<%= form_with(model: @deal, url: deal_categories_url, method: :post) do |form| %>
  <div class="d-flex justify-content-between top p-2">
    <%= link_to root_path, class: 'text-light h1' do %>
        <i class="bi bi-arrow-left"></i>
    <% end %>
    <h2 class='text-light h1'>NEW DEAL</h2>
    <%= form.submit 'Save'%>
  </div>
   <div class="p-2">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name', required: true %>
   </div>
   <div class="p-2">
    <%= form.number_field :amount, class: 'form-control', placeholder: 'Amount', required: true %>
   </div>
   <div class="p-2">
      <%= select_tag "category", options_for_select(@categories.map { |category| [category.name, category.id] }), 
      {prompt: 'Select Category', required: true, 
       class: "col-12 p-2 border rounded dropdown-toggle"} %>
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> %>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
   <body>
    <main>
      <div id="off-canvas" class="pt-5 ps-3">
        <p><i class="bi bi-person-circle"></i>Welcome <%=@name%></p>
           <i class="bi bi-lg"></i>
        <ul class="list-unstyled menu ps-2">
          <li class="mb-3"><%=link_to "Home" , root_path, class: "text-light text-decoration-none" %></li>
          <li><%= link_to "Logout" ,  destroy_user_session_path, method: :delete, class: "text-light text-decoration-none" %><li>
        </ul>
      </div>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </main>
  </body>
</html>